### ISSUE TITLE
Feature request: media player selector

### ISSUE THREAD

**Issue by FragMenthor** [JurajNyiri/PlexMeetsHomeAssistant#46]
Hello! I really love your card, changed the way I use Plex and HA. But I have multiple players at home, and would like to select on the card which player to use  (maybe all visible identified with different icons, with the one chosen with some kind of highlight).
Of maybe the chance to template the player, so that we can have a selector in other card and use that entity to identify the player - maybe that's no possible, I don't know)
And thanks again for this card!!! Love it!

**Comment by JurajNyiri** [comment]
Hey, thank you for the suggestment!

Selecting player goes against some ideas of the card. Currently when you specify multiple entities it chooses the first available one. Modifying this behaviour is possible but would cause a bit of confusion.

I do really like the idea of templating and have been thinking about it a lot already, I just didn't get to implementing it. I think we can add support for input_select elements and templates. Another use case for this is a room awareness along with template sensor. So that when I am with tablet/phone in living room, it uses that TV. When in guest room, it uses that one.

**Comment by JurajNyiri** [comment]
Now available in [3.2](https://github.com/JurajNyiri/PlexMeetsHomeAssistant/releases/tag/3.2).
